#!/bin/sh
# Copyright 2019 簡煒航 (Jian Weihang) <https://tonytonyjan.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

if test -z $PTX_APP_ID || test -z $PTX_APP_KEY || test -z $1; then
  cat <<MSG >&2
Usage: $0 API_PATH
Environment:
    PTX_APP_ID - L1/L2 Application ID
    PTX_APP_KEY - L1/L2 Application KEY
Example:
    env PTX_APP_ID=YOUR_ID PTX_APP_KEY=YOUR_KEY $0 '/v2/Air/FIDS/Airport/Departure?\$top=3'
MSG
  exit 1
fi

now=$(env TZ=GMT date '+%a, %d %b %Y %T %Z') &&
  signature=$(printf "x-date: $now" | openssl sha1 -binary -hmac $PTX_APP_KEY | base64) &&
  curl -sSX GET \
    --header 'Accept: application/json' \
    --header "Authorization: hmac username=\"$PTX_APP_ID\", algorithm=\"hmac-sha1\", headers=\"x-date\", signature=\"$signature\"" \
    --header "x-date: $now" \
    --compressed \
    "https://ptx.transportdata.tw/MOTC$1"
